version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - apt update
      - apt install docker.io
      - service docker start
      - sudo usermod -aG docker $USER
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

  build:
    commands:
      - echo Building Docker image...
      - docker build -t dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION