version: 0.2

phases:
  pre_build:
    commands:
      - echo We are on $(uname -a)
      - echo Installing docker...
      - yum update
      - yum install -y docker
      - systemctl start docker
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

  build:
    commands:
      - echo Building Docker image...
      - docker build -t dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION