version: 0.2

phases:
  install:
    runtime-versions:
        docker: 20
    commands:
      - echo Installing Docker...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker image...
      - docker build -t dijey099/sokola:latest .
      - docker tag dijey099/sokola:latest dijey099/sokola:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push dijey099/sokola:latest
      - docker push dijey099/sokola:$IMAGE_TAG