version: 0.2

phases:
  install:
    commands:
      - echo Downloading Docker...
      - curl -fsSL https://get.docker.com -o install-docker.sh
      - echo Installing Docker...
      - sh install-docker.sh
      - sudo usermod -aG docker $USER
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

  build:
    commands:
      - echo Building Docker image...
      - docker build -t dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push dijey099/sokola:$CODEBUILD_RESOLVED_SOURCE_VERSION