apiVersion: apps/v1
kind: Deployment
metadata:
  name: sokola-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sokola-app
  template:
    metadata:
      labels:
        app: sokola-app
    spec:
      containers:
        - name: sokola-container
          image: dijey099/sokola:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sokola-service
spec:
  selector:
    app: sokola-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
